"""add_conversations_models

Revision ID: 06d0a1a77f5c
Revises: d1760f328ee3
Create Date: 2025-10-27 23:41:13.562144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06d0a1a77f5c'
down_revision = 'd1760f328ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('title', sa.Unicode(length=200), nullable=False, comment='会话标题'),
    sa.Column('topic', sa.Unicode(length=500), nullable=False, comment='视频主题'),
    sa.Column('status', sa.Integer(), nullable=False, comment='会话状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('user_style_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False, comment='是否已分析'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_style_profiles_created_at'), 'user_style_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_style_profiles_updated_at'), 'user_style_profiles', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_style_profiles_user_id'), 'user_style_profiles', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.Unicode(length=20), nullable=False, comment='消息角色'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_updated_at'), 'messages', ['updated_at'], unique=False)
    op.create_table('scripts',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True, comment='关联的会话ID'),
    sa.Column('title', sa.Unicode(length=200), nullable=False, comment='脚本标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='脚本内容'),
    sa.Column('format_type', sa.Unicode(length=50), nullable=False, comment='格式类型'),
    sa.Column('status', sa.Integer(), nullable=False, comment='脚本状态'),
    sa.Column('quality_score', sa.Integer(), nullable=True, comment='质量评分'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_conversation_id'), 'scripts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_scripts_created_at'), 'scripts', ['created_at'], unique=False)
    op.create_index(op.f('ix_scripts_status'), 'scripts', ['status'], unique=False)
    op.create_index(op.f('ix_scripts_updated_at'), 'scripts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_scripts_user_id'), 'scripts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_user_id'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_updated_at'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_status'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_created_at'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_conversation_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_messages_updated_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_style_profiles_user_id'), table_name='user_style_profiles')
    op.drop_index(op.f('ix_user_style_profiles_updated_at'), table_name='user_style_profiles')
    op.drop_index(op.f('ix_user_style_profiles_created_at'), table_name='user_style_profiles')
    op.drop_table('user_style_profiles')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
