"""add_script_research_tables

Revision ID: 254d4e3df0ee
Revises: 06d0a1a77f5c
Create Date: 2025-12-02 21:46:14.825509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '254d4e3df0ee'
down_revision = '06d0a1a77f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_researches',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('script_id', sa.BigInteger(), nullable=False, comment='研究的脚本ID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='研究对话的会话ID'),
    sa.Column('status', sa.Integer(), nullable=False, comment='研究状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_researches_conversation_id'), 'script_researches', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_script_researches_created_at'), 'script_researches', ['created_at'], unique=False)
    op.create_index(op.f('ix_script_researches_script_id'), 'script_researches', ['script_id'], unique=False)
    op.create_index(op.f('ix_script_researches_status'), 'script_researches', ['status'], unique=False)
    op.create_index(op.f('ix_script_researches_updated_at'), 'script_researches', ['updated_at'], unique=False)
    op.create_index(op.f('ix_script_researches_user_id'), 'script_researches', ['user_id'], unique=False)
    
    # 添加 conversation_type 字段（先允许 NULL）
    op.add_column('conversations', sa.Column('conversation_type', sa.Integer(), nullable=True, comment='对话类型：10=创作对话, 20=研究对话'))
    
    # 为现有数据设置默认值（创作对话）
    op.execute("UPDATE conversations SET conversation_type = 10 WHERE conversation_type IS NULL")
    
    # 将字段改为 NOT NULL
    op.alter_column('conversations', 'conversation_type', nullable=False)
    
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_column('conversations', 'conversation_type')
    op.drop_index(op.f('ix_script_researches_user_id'), table_name='script_researches')
    op.drop_index(op.f('ix_script_researches_updated_at'), table_name='script_researches')
    op.drop_index(op.f('ix_script_researches_status'), table_name='script_researches')
    op.drop_index(op.f('ix_script_researches_script_id'), table_name='script_researches')
    op.drop_index(op.f('ix_script_researches_created_at'), table_name='script_researches')
    op.drop_index(op.f('ix_script_researches_conversation_id'), table_name='script_researches')
    op.drop_table('script_researches')
    # ### end Alembic commands ###
